['dir']
ian_drifter_data = 'data/drifter_data/hurricane_ian_drifter_data_v2.pickle'
idalia_drifter_data = 'data/drifter_data/hurricane_idalia_drifter_data_v3.pickle'
lee_drifter_data = 'data/drifter_data/hurricane_lee_drifter_data_v1.pickle'
francine_drifter_data = 'data/drifter_data/hurricane_francine_drifter_data_v0.pickle'
helene_drifter_data = 'data/drifter_data/hurricane_helene_drifter_data_v0.pickle'
milton_drifter_data = 'data/drifter_data/hurricane_milton_drifter_data_v0.pickle'
francine_submersibles_kml = 'data/submersibles/francine_submersibles.kml'
helene_submersibles_kml = 'data/submersibles/helene_submersibles.kml'
milton_submersibles_kml = 'data/submersibles/milton_submersibles.kml'
ian_best_track = 'data/nhc/al092022_best_track/'
idalia_best_track = 'data/nhc/al102023_best_track/'
lee_best_track = 'data/nhc/al132023_best_track/'
francine_best_track = 'data/nhc/al062024_best_track/'
helene_best_track = 'data/nhc/al092024_best_track/'
milton_best_track = 'data/nhc/al142024_best_track/'
ian_bathymetry = 'data/bathymetry/gebco_2022_n30.5_s23.0_w-88.0_e-80.0.nc'
idalia_bathymetry = 'data/bathymetry/gebco_2023_n31.0_s25.0_w-87.0_e-81.0.nc'
lee_bathymetry = 'data/bathymetry/gebco_2023_n45.0_s38.0_w-75.0_e-65.0.nc'
francine_bathymetry = 'data/bathymetry/gebco_2024_n32.5_s24.5_w-98.0_e-87.0.nc'
helene_bathymetry = 'data/bathymetry/gebco_2024_n32.5_s24.0_w-89.0_e-79.0.nc'
milton_bathymetry = 'data/bathymetry/gebco_2024_n30.5_s23.0_w-88.0_e-80.0.nc'
ibtracs = 'data/ibtracs.last3years.list.v04r01.csv'
nearshore_sensors = 'data/nearshore_sensors/NOPP_Task3B_AllSensors.csv'
